# Generated by Django 4.1.7 on 2023-03-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_alter_album_id_alter_music_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='musics/'),
        ),
    ]
